name: GeneralisedSwap
version: '1.0'
main: com.shard.generalswap.SwapPlugin
api-version: '1.21'
authors: [Shard0fLightning]
depend: [ManhuntPlus]
commands:
  gswap:
    description: control generalised swap

